### ISSUE TITLE
🐛 Issue: Publish GitHub Action to Push Package to GitHub Package Registry

### ISSUE THREAD

**Issue by wreiske** [bluehive-health/zipcodes#6]
**Summary:**
When trying to install `@bluehive/bluehive-zipcodes@8.0.4` via `npm.pkg.github.com`, we’re getting a 404 error. It appears the package is not published under the `@bluehive` scope or is missing from the GitHub Package Registry entirely.

**Error Trace:**

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/download/@bluehive/bluehive-zipcodes/8.0.4/... - npm package "bluehive-zipcodes" does not exist under owner "bluehive"
npm ERR! 404
npm ERR! 404 '@bluehive/bluehive-zipcodes@8.0.4' is not in this registry.
```

**Suggested Fix:**

Please add a **GitHub Action** workflow to this repo that:

1. Runs on new tagged releases.
2. Authenticates with `NODE_AUTH_TOKEN` or a GitHub PAT with `write:packages`.
3. Builds and publishes the package to `https://npm.pkg.github.com`.

**Example Workflow:**

```yaml
name: Publish to GitHub Package Registry

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: npm ci

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Additional Notes:**

* Make sure the `package.json` has the correct `name`, scoped as `"@bluehive/bluehive-zipcodes"`, and the `publishConfig` is set correctly:

  ```json
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/"
  }
  ```
* Confirm the repository is public or the consuming token has access if private.
